# Site settings
title: Nicole Wang
email: wangnico@usc.edu
description: > # keep this and put description below
  Technical Artist
  Programmer
  Artist
url: "https://NicoWWW.com" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/rui-nicole-wang-628543293/"
footer_text: "Â© BY NICOLE WANG 2024."

# Build settings
markdown: kramdown
permalink: pretty
